// <auto-generated />
using ElonMusk_portfolioWeb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ElonMusk_portfolioWeb.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240917162749_projectvalues")]
    partial class projectvalues
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ElonMusk_portfolioWeb.Models.Enitites.Contact", b =>
                {
                    b.Property<int>("ContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContactId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ContactId");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("ElonMusk_portfolioWeb.Models.Enitites.Detail", b =>
                {
                    b.Property<int>("DetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DetailId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Occupation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DetailId");

                    b.ToTable("Details");
                });

            modelBuilder.Entity("ElonMusk_portfolioWeb.Models.Enitites.Login", b =>
                {
                    b.Property<int>("LoginId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LoginId"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LoginId");

                    b.ToTable("Logins");
                });

            modelBuilder.Entity("ElonMusk_portfolioWeb.Models.Enitites.Project", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProjectId");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            ProjectId = 1,
                            Description = "Cybertruck: Tesla's all-electric Cybertruck is set to begin production,with Musk highlighting its durability and futuristic design.\r\nThe vehicle aims to disrupt the traditional truck market with its unique features and electric powertrain.",
                            ImageUrl = "https://wallpaperaccess.com/full/846579.jpg",
                            Name = "Tesla"
                        },
                        new
                        {
                            ProjectId = 2,
                            Description = "Starship: SpaceX is actively working on Starship, a fully reusable spacecraft designed for missions to Mars and beyond. The spacecraft aims to make space travel more affordable and sustainable. Test flights and development are ongoing, with plans for operational missions in the near future.\r\n",
                            ImageUrl = "https://i.pinimg.com/736x/b6/12/2e/b6122e067cad4cde07468d6627544989.jpg",
                            Name = "SpaceX"
                        },
                        new
                        {
                            ProjectId = 3,
                            Description = "Brain-Computer Interfaces: Neuralink is working on advanced brain-computer interface technologies. The company aims to develop devices that can treat neurological conditions and eventually enable direct communication between the human brain and computers.",
                            ImageUrl = "https://th.bing.com/th/id/R.1e3159c54758a954464cdfe581cc387a?rik=HMGyr2Hl2hcBqg&riu=http%3a%2f%2fstatic1.squarespace.com%2fstatic%2f61422d4c713a6811602aa6b0%2ft%2f6151f784a101dd20189704a4%2f1632761732961%2fNeurolink%2blogo.jpg%3fformat%3d1500w&ehk=aYcTvTWshEucBV4Xn0jNeBM0HKq2wTwfx4HQfJlx0xA%3d&risl=&pid=ImgRaw&r=0",
                            Name = "Neuralink"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
